### ISSUE TITLE
Краш после нажатия кнопки для получения адреса выделенного здания

### ISSUE THREAD

**Issue by deevroman** [micronull/JOSM-Russia-address-helper-plugin#14]
Если правильно помню, то на этом доме вылетело https://www.openstreetmap.org/way/186255228
```
{{{
Revision:18894
Is-Local-Build:true
Build-Date:2023-11-06 13:31:31

Identification: JOSM/1.5 (18894 SVN ru) Mac OS X 14.0
OS Build number: macOS 14.0 (23A344)
Memory Usage: 2818 MB / 4096 MB (794 MB allocated, but free)
Java version: 21.0.1+12-LTS, Azul Systems, Inc., OpenJDK 64-Bit Server VM
Look and Feel: javax.swing.plaf.metal.MetalLookAndFeel
Screen: Display 1 1512×982 (scaling 2.00×2.00)
Maximum Screen Size: 1512×982
Best cursor sizes: 16×16→16×16, 32×32→32×32
System property file.encoding: UTF-8
System property sun.jnu.encoding: UTF-8
Locale info: ru_RU
Numbers with default locale: 1234567890 -> 1234567890
VM arguments: [-Djpackage.app-version=18894, --add-modules=java.scripting,java.sql,javafx.controls,javafx.media,javafx.swing,javafx.web, --add-exports=java.base/sun.security.action=ALL-UNNAMED, --add-exports=java.desktop/com.apple.eawt=ALL-UNNAMED, --add-exports=java.desktop/com.sun.imageio.plugins.jpeg=ALL-UNNAMED, --add-exports=java.desktop/com.sun.imageio.spi=ALL-UNNAMED, --add-opens=java.base/java.lang=ALL-UNNAMED, --add-opens=java.base/java.nio=ALL-UNNAMED, --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED, --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED, --add-opens=java.desktop/javax.imageio.spi=ALL-UNNAMED, --add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED, --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED, -Djpackage.app-path=/Applications/JOSM.app/Contents/MacOS/JOSM]
Dataset consistency test: No problems found

Plugins:
+ CADTools (1008)
+ DirectDownload (36178)
+ DirectUpload (36178)
+ FastDraw (36126)
+ MapRoulette (26)
+ Mapillary (2.2.0)
+ OpeningHoursEditor (36126)
+ PolygonCutOut (v0.7.3)
+ apache-commons (36176)
+ buildings_tools (36178)
+ changeset-viewer (0.0.7)
+ changessum (v0.1.1)
+ conflation (0.6.11)
+ continuosDownload (103)
+ editgpx (36126)
+ flatlaf (36176)
+ jts (36004)
+ mbtiles (v2.6.1)
+ measurement (36126)
+ pmtiles (36156)
+ reverter (36126)
+ russia-address-helper (0.9.0.0)
+ turnrestrictions (36178)
+ undelete (36126)
+ utilsplugin2 (36178)
+ waydownloader (36126)
+ wikipedia (605)

Tagging presets:
+ https://raw.githubusercontent.com/ruosm-presets/literan-moscow/master/russian_shops.xml
+ https://josm.openstreetmap.de/josmfile?page=Presets/OneClick&zip=1

Map paint styles:
+ https://josm.openstreetmap.de/josmfile?page=Styles/Potlatch2&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Styles/NewHighwayColors&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/FixmeAndNote&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/MapWithAI&zip=1
+ https://raw.githubusercontent.com/species/josm-preset-traffic_sign_direction/master/direction.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Waterways&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/HiDPISupport&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/HighwayAreas&zip=1

Last errors/warnings:
- 04893.178 E: 	at org.openstreetmap.josm.data.UndoRedoHandler.afterAdd(UndoRedoHandler.java:321)
- 04893.178 E: 	at org.openstreetmap.josm.data.UndoRedoHandler.add(UndoRedoHandler.java:355)
- 04893.178 E: 	at org.openstreetmap.josm.plugins.dl.russiaaddresshelper.models.Buildings$load$1.invokeSuspend(Buildings.kt:152)
- 04893.178 E: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
- 04893.178 E: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
- 04893.178 E: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
- 04893.178 E: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
- 04893.178 E: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
- 04893.178 E: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
- 04893.438 E: Handled by bug report queue: java.lang.NullPointerException: p["egrn_name"] must not be null



=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (38) of main
java.lang.NullPointerException: p["egrn_name"] must not be null
	at org.openstreetmap.josm.plugins.dl.russiaaddresshelper.parsers.ParsedPlace.getOsmObjectsByType(ParsedPlace.kt:216)
	at org.openstreetmap.josm.plugins.dl.russiaaddresshelper.parsers.ParsedPlace.getMatchingPrimitives(ParsedPlace.kt:224)
	at org.openstreetmap.josm.plugins.dl.russiaaddresshelper.validation.EGRNStreetOrPlaceTooFarTest.visit(EGRNStreetOrPlaceTooFarTest.kt:82)
	at org.openstreetmap.josm.data.osm.Way.accept(Way.java:180)
	at org.openstreetmap.josm.data.validation.Test.visit(Test.java:216)
	at org.openstreetmap.josm.data.validation.ValidationTask.realRun(ValidationTask.java:136)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:94)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:142)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
}}}

```

**Comment by TakutoRU** [comment]
Обновите версию плагина, этот вылет починен в версии 0.9.0.1, а у вас russia-address-helper (0.9.0.0)
В любом случае, спасибо за обратную связь.
