### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Miroff** [micronull/JOSM-Russia-address-helper-plugin#2]
Воспроизводится нестабильно, просто в процессе работы иногда плагин падает. Повторный запуск на том же объекте работает. 

Проверял в области: 54.4901712,83.4166259,54.4925021,83.4224602

```
{{{
Relative:URL: ^/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2022-01-27 23:43:27 +0100 (Thu, 27 Jan 2022)
Revision:18367
Build-Date:2022-01-28 02:31:10
URL:https://josm.openstreetmap.de/svn/trunk

Identification: JOSM/1.5 (18367 en) Linux Ubuntu 20.04.3 LTS
Memory Usage: 4096 MB / 4096 MB (2815 MB allocated, but free)
Java version: 14.0.1+7, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Look and Feel: javax.swing.plaf.metal.MetalLookAndFeel
Screen: :0.0 1920×1080 (scaling 1.00×1.00)
Maximum Screen Size: 1920×1080
Best cursor sizes: 16×16→16×16, 32×32→32×32
Environment variable LANG: en_US.UTF-8
System property file.encoding: UTF-8
System property sun.jnu.encoding: UTF-8
Locale info: en_US
Numbers with default locale: 1234567890 -> 1234567890
Desktop environment: ubuntu:GNOME
libcommons-logging-java: libcommons-logging-java:-
fonts-noto: fonts-noto:-
VM arguments: [-Djava.net.preferIPv4Stack=true]
Dataset consistency test: No problems found

Plugins:
+ FastDraw (35893)
+ OpeningHoursEditor (35893)
+ apache-commons (35893)
+ apache-http (35893)
+ buildings_tools (35893)
+ easypresets (1623509627)
+ ejml (35893)
+ ext_tools (35893)
+ jaxb (35893)
+ jna (35893)
+ jogl (1.2.3)
+ jts (35893)
+ log4j (35893)
+ measurement (35893)
+ merge-overlap (35893)
+ reltoolbox (35893)
+ russia-address-helper (0.6.0.1)
+ scripting (30798)
+ turnrestrictions (35893)
+ utilsplugin2 (35893)
+ wikipedia (605)

Tagging presets:
+ https://raw.githubusercontent.com/OpenSeaMap/josm/master/Presets_Sport.xml
+ https://raw.githubusercontent.com/ruosm-presets/literan-moscow/master/russian_shops.xml
+ ${HOME}/sandbox/osm-tourism-preset/wood.xml
+ ${HOME}/Downloads/preset-power-tower.zip
+ ${HOME}/Downloads/Power.zip
+ <josm.pref>/EasyPresets.xml

Map paint styles:
- https://josm.openstreetmap.de/josmfile?page=Styles/Whitewater&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Mountains&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/PublicTransport&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/PowerMapping&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Power&zip=1
- ${HOME}/sandbox/josm_mapcss/authoring.mapcss
- ${HOME}/sandbox/osm-tourism-preset/wood.mapcss
- ${HOME}/Downloads/style-power-tower-solid.zip
- ${HOME}/Downloads/style-power-voltage-color.zip
- https://josm.openstreetmap.de/josmfile?page=Styles/Enhanced_Lane_and_Road_Attributes&zip=1

Validator rules:
+ https://raw.githubusercontent.com/zetx16/Josm-HnumbValidator/master/ru-housenumber.validator.mapcss

Last errors/warnings:
- 00021.438 W: [WAY] Section: Could not get presets icon http://dev.openseamap.org/josm/icons/section16.png
- 00109.264 W: com.github.kittinunf.fuel.core.BubbleFuelError: Connection refused. Cause: com.github.kittinunf.fuel.core.FuelError: Connection refused. Cause: java.net.ConnectException: Connection refused
- 00110.774 W: com.github.kittinunf.fuel.core.BubbleFuelError: Connection refused. Cause: com.github.kittinunf.fuel.core.FuelError: Connection refused. Cause: java.net.ConnectException: Connection refused
- 00110.852 W: com.github.kittinunf.fuel.core.BubbleFuelError: Connection refused. Cause: com.github.kittinunf.fuel.core.FuelError: Connection refused. Cause: java.net.ConnectException: Connection refused
- 00110.872 E: Handled by bug report queue: java.lang.NullPointerException
- 00110.945 W: com.github.kittinunf.fuel.core.BubbleFuelError: Connection refused. Cause: com.github.kittinunf.fuel.core.FuelError: Connection refused. Cause: java.net.ConnectException: Connection refused
- 00374.758 W: com.github.kittinunf.fuel.core.BubbleFuelError: Connection refused. Cause: com.github.kittinunf.fuel.core.FuelError: Connection refused. Cause: java.net.ConnectException: Connection refused
- 00408.312 W: com.github.kittinunf.fuel.core.BubbleFuelError: Connection refused. Cause: com.github.kittinunf.fuel.core.FuelError: Connection refused. Cause: java.net.ConnectException: Connection refused
- 00425.787 W: com.github.kittinunf.fuel.core.BubbleFuelError: Connection refused. Cause: com.github.kittinunf.fuel.core.FuelError: Connection refused. Cause: java.net.ConnectException: Connection refused
- 00443.562 E: Handled by bug report queue: java.lang.NullPointerException



=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: DefaultDispatcher-worker-4 (156) of main
java.lang.NullPointerException
	at org.openstreetmap.josm.plugins.dl.russiaaddresshelper.tools.DeleteDoubles$clear$1.invoke(DeleteDoubles.kt:23)
	at org.openstreetmap.josm.plugins.dl.russiaaddresshelper.tools.DeleteDoubles$clear$1.invoke(DeleteDoubles.kt:22)
	at kotlin.collections.CollectionsKt__MutableCollectionsKt.filterInPlace$CollectionsKt__MutableCollectionsKt(MutableCollections.kt:285)
	at kotlin.collections.CollectionsKt__MutableCollectionsKt.removeAll(MutableCollections.kt:269)
	at org.openstreetmap.josm.plugins.dl.russiaaddresshelper.tools.DeleteDoubles.clear(DeleteDoubles.kt:22)
	at org.openstreetmap.josm.plugins.dl.russiaaddresshelper.models.Buildings.sanitize(Buildings.kt:216)
	at org.openstreetmap.josm.plugins.dl.russiaaddresshelper.models.Buildings.access$sanitize(Buildings.kt:28)
	at org.openstreetmap.josm.plugins.dl.russiaaddresshelper.models.Buildings$load$1.invokeSuspend(Buildings.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
}}}
```

**Comment by micronull** [comment]
@Miroff спасибо! 
Упал во время удаления дублей. Это я не проверил( 
Буду писать тесты для этого кейса и фиксить.

Пока могу посоветовать выключить галочку удаления дублей в настройках плагина.
