### ISSUE TITLE
java.util.NoSuchElementException

### ISSUE THREAD

**Issue by micronull** [micronull/JOSM-Russia-address-helper-plugin#9]
При получении адреса "На месте клика", выскакивает java.util.NoSuchElementException.

Населенный пункт - Зеленый Лог, Полевской район, Свердловская область.

ЕГРН без улицы, вероятно дело в этом.

Судя по логам получено значение: `Свердловская область, г. Полевской, п. Зеленый Лог, 12А`

```
{{{
Revision:18746
Build-Date:2023-06-05 12:33:50

Identification: JOSM/1.5 (18746 ru) Windows 11 64-Bit
OS Build number: Windows 10 Pro 2009 (22000)
Memory Usage: 918 MB / 4086 MB (180 MB allocated, but free)
Java version: 17.0.7+7-LTS, Azul Systems, Inc., OpenJDK 64-Bit Server VM
Look and Feel: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
Screen: \Display0 1920×1080 (scaling 1.00×1.00)
Maximum Screen Size: 1920×1080
Best cursor sizes: 16×16→32×32, 32×32→32×32
System property file.encoding: Cp1252
System property sun.jnu.encoding: Cp1252
Locale info: ru_RU
Numbers with default locale: 1234567890 -> 1234567890
VM arguments: [-Djpackage.app-version=1.5.18746, --add-modules=java.scripting,java.sql,javafx.controls,javafx.media,javafx.swing,javafx.web, --add-exports=java.base/sun.security.action=ALL-UNNAMED, --add-exports=java.desktop/com.sun.imageio.plugins.jpeg=ALL-UNNAMED, --add-exports=java.desktop/com.sun.imageio.spi=ALL-UNNAMED, --add-opens=java.base/java.lang=ALL-UNNAMED, --add-opens=java.base/java.nio=ALL-UNNAMED, --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED, --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED, --add-opens=java.desktop/javax.imageio.spi=ALL-UNNAMED, --add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED, --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED, -Djpackage.app-path=%UserProfile%\AppData\Local\JOSM\JOSM.exe]
Dataset consistency test: No problems found

Plugins:
+ DirectDownload (36031)
+ OpeningHoursEditor (36079)
+ apache-commons (36034)
+ apache-http (35924)
+ buildings_tools (36011)
+ editgpx (36079)
+ imagery_offset_db (36079)
+ jna (36005)
+ mapwithai (794)
+ russia-address-helper (0.8.5.1)
+ utilsplugin2 (36079)

Tagging presets:
+ https://raw.githubusercontent.com/ruosm-presets/literan-moscow/master/russian_shops.xml
+ https://josm.openstreetmap.de/josmfile?page=Presets/Payment_Method_RU&zip=1

Map paint styles:
+ https://josm.openstreetmap.de/josmfile?page=Styles/Coloured_Streets&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/MapWithAI&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Styles/PriorityRoad&zip=1

Last errors/warnings:
- 02367.970 E: EGRN-PLUGIN Cannot extract street name from EGRN address Свердловская область, г. Полевской, п. Зеленый Лог, 12А
- 02367.973 E: Handled by bug report queue: java.util.NoSuchElementException
- 02423.329 W: EGRN-Plugin Error connection refused, retries 5
- 02426.535 W: EGRN-Plugin Error connection refused, retries 4
- 02429.743 W: EGRN-Plugin Error connection refused, retries 3
- 02430.946 E: Handled by bug report queue: java.util.NoSuchElementException
- 02532.273 W: EGRN-Plugin Error connection refused, retries 5
- 02536.280 W: EGRN-Plugin Error connection refused, retries 4
- 02540.285 W: EGRN-Plugin Error connection refused, retries 3
- 02541.492 E: Handled by bug report queue: java.util.NoSuchElementException



=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (22) of main
java.util.NoSuchElementException
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at org.openstreetmap.josm.command.SequenceCommand.<init>(SequenceCommand.java:59)
	at org.openstreetmap.josm.command.SequenceCommand.<init>(SequenceCommand.java:68)
	at org.openstreetmap.josm.plugins.dl.russiaaddresshelper.actions.ClickAction$mouseClicked$1.invoke(ClickAction.kt:132)
	at org.openstreetmap.josm.plugins.dl.russiaaddresshelper.actions.ClickAction$mouseClicked$1.invoke(ClickAction.kt:82)
	at com.github.kittinunf.result.ResultKt.success(Result.kt:148)
	at org.openstreetmap.josm.plugins.dl.russiaaddresshelper.actions.ClickAction.mouseClicked(ClickAction.kt:82)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
}}}
```

**Comment by TakutoRU** [comment]
Не стоит проверка на пустой список добавляемых точек, а не заметил раньше, потому что у меня включена настройка "Генерировать точки для нераспознанных адресов", в результате багу не ловим.
Будет исправлено в следующем релизе, пока workaraund - включить эту настройку.

**Comment by TakutoRU** [comment]
Исправлено в 0.9.0.0
